services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: (à générer avec `php artisan key:generate --show`)
      - key: DB_CONNECTION
        value: mysql

